name: Docker Build Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nginx-log-monitor:latest
    - name: Try to run --help
      run: docker run --rm -i nginx-log-monitor:latest --help
